remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Easy Work Makes the Recipe Work (Or Does It?) 
description: Final Project for DSC80 at UCSD.
